version: 2.1
description: Golang test job
orbs:
    go: circleci/go@1.5.0

jobs:
  test:
    executor:
      name: go/default
      tag: '1.15'
    steps:
      - checkout
      - go/mod-download-cached
      - go/test
