version: 2.1
orbs:
  go: teka23/golang-test-job@0.0.1
  aws-ecr: circleci/aws-ecr@6.15.0
  aws-ecs: circleci/aws-ecs@1.4.0
workflows:
  test-build:
    jobs:
      - go/test
      - aws-ecr/build-and-push-image:
          requires: [go/test]
          repo: "orbs"
          tag: "${CIRCLE_SHA1}"
      - aws-ecs/deploy-service-update:
          requires: [aws-ecr/build-and-push-image]
          family: "orbs-task-definition"
          service-name: "orbs-service"
          cluster-name: "orbs-cluster"
          container-image-name-updates: "container=orbs,tag=${CIRCLE_SHA1}"
